using BogusLibrary.Classes;
using BogusLibrary.Models;
using Shouldly;
using TestProject1.Base;
#pragma warning disable MSTEST0017

namespace TestProject1;

[TestClass]
public sealed class BogusGenerationTests
{
    
    /// <summary>
    /// Validates that the first name of the first generated <see cref="Human"/> object
    /// matches the expected value.
    /// </summary>
    /// <remarks>
    /// This test method uses the <see cref="HumanGenerator"/> to create a single
    /// <see cref="Human"/> object and verifies that its <see cref="Human.FirstName"/>
    /// property is correctly initialized.
    /// </remarks>
    /// <exception cref="AssertFailedException">
    /// Thrown if the actual first name does not match the expected value.
    /// </exception>
    [TestMethod]
    [TestTraits(Trait.Bogus)]
    public void ValidateHumanGeneratorFirstItemFirstName()
    {
        // arrange
        var human = HumanGenerator.Create(1);
        var expected = "Marlon";

        // act
        var firstName = human.FirstOrDefault().FirstName;

        // assert
        Assert.AreEqual(firstName, expected);

    }

    /// <summary>
    /// Validates that the last name generated by the <see cref="HumanGenerator"/> matches
    /// the expected value.
    /// </summary>
    /// <remarks>
    /// This test method uses the <see cref="HumanGenerator.Create(int, bool)"/> method
    /// to generate a list of  <see cref="Human"/> objects and verifies that the
    /// first generated human's last name matches the expected value.
    ///
    /// Uses the Shouldly assertion library to compare the actual last name with
    /// the expected value.
    /// 
    /// </remarks>
    [TestMethod]
    [TestTraits(Trait.BogusShouldly)]
    public void ValidateHumanGeneratorFirstName()
    {
        // arrange
        var human = HumanGenerator.Create(1);
        var expected = "Marlon";

        // act
        var firstName = human.FirstOrDefault().FirstName;

        // assert
        firstName.ShouldBe(expected);
    }
}
