using System.Diagnostics;
using BogusLibrary.Classes;
using BogusLibrary.Models;
using KellermanSoftware.CompareNetObjects;
using Serilog;
using Shouldly;
using TestProject1.Base;
using TestProject1.Classes;

namespace TestProject1;

[TestClass]
public sealed partial class BogusGenerationTests : TestBase
{
    
    /// <summary>
    /// Validates that the first name of the first generated <see cref="Human"/> object
    /// matches the expected value.
    /// </summary>
    /// <remarks>
    /// This test method uses the <see cref="HumanGenerator"/> to create a single
    /// <see cref="Human"/> object and verifies that its <see cref="Human.FirstName"/>
    /// property is correctly initialized.
    /// </remarks>
    /// <exception cref="AssertFailedException">
    /// Thrown if the actual first name does not match the expected value.
    /// </exception>
    [TestMethod]
    [TestTraits(Trait.Bogus)]
    public void ValidateHumanGeneratorFirstItemFirstName()
    {
        // arrange
        var human = _human;
        const string expected = "Marlon";

        // act
        var firstName = human.FirstName;

        // assert
        Assert.AreEqual(expected, firstName);

    }

    /// <summary>
    /// Validates that the last name generated by the <see cref="HumanGenerator"/> matches
    /// the expected value.
    /// </summary>
    /// <remarks>
    /// This test method uses the <see cref="HumanGenerator.Create(int, bool)"/> method
    /// to generate a list of  <see cref="Human"/> objects and verifies that the
    /// first generated human's last name matches the expected value.
    ///
    /// Uses the Shouldly assertion library to compare the actual last name with
    /// the expected value.
    /// 
    /// </remarks>
    [TestMethod]
    [TestTraits(Trait.BogusShouldly)]
    public void ValidateHumanGeneratorFirstName()
    {
        // arrange
        var human = _human;
        const string expected = "Marlon";

        // act
        var firstName = human.FirstName;

        // assert
        firstName.ShouldBe(expected);
    }

    [TestMethod]
    [TestTraits(Trait.BogusShouldly)]
    public void ValidateHumanGeneratorNotFirstName()
    {
        // arrange
        var human = _human;
        const string expected = "Marlon";

        // act
        human.FirstName = "NotMarlon"; // change local human not to change _human
        var firstName = human.FirstName;

        // assert
        firstName.ShouldNotBe(expected);

        human.FirstName = "Marlon";

    }

    [TestMethod]
    [TestTraits(Trait.Keller)]
    public void CompareHumans()
    {
        // arrange
        var human = _human;
        CompareLogic compare = new();
        compare.Config.MembersToIgnore.Add("*Birth*");

        // act
        human.FirstName = "Marlon";
        ComparisonResult result = compare.Compare(human, _testHuman);

        if (!result.HasDifferences())
        {
            Log.Information(result.DifferencesString);
        }

        // assert
        Assert.IsTrue(result.AreEqual);

    }
}
