// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using ConsoleConfigurationLibrary.Classes;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using EntityCoreFileLogger;
using WorkingWithDatesAndTime.Classes.Configuration;
using WorkingWithDatesAndTime.Models;
using Microsoft.Extensions.Logging;

namespace WorkingWithDatesAndTime.Data;

public partial class Context : DbContext
{
    public Context()
    {
    }

    public Context(DbContextOptions<Context> options)
        : base(options)
    {
    }

    public virtual DbSet<Calendar> Calendar { get; set; }

    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        if (optionsBuilder.IsConfigured) return;

        optionsBuilder.UseSqlite(DataConnections.Instance.MainConnection);

        // Enable sensitive data logging only in Development environment
        if (Debugger.IsAttached)
        {
            //optionsBuilder
            //    .EnableSensitiveDataLogging()
            //    .LogTo(message => Debug.WriteLine(message),
            //    [
            //        DbLoggerCategory.Database.Command.Name
            //    ], LogLevel.Information);

            optionsBuilder
                .EnableSensitiveDataLogging()
                .LogTo(new DbContextToFileLogger().Log, new[]
                    {
                        DbLoggerCategory.Database.Command.Name
                    },
                    LogLevel.Information);

        }

        // Log database commands to file
        //optionsBuilder.LogTo(new DbContextToFileLogger().Log,
        //[
        //    DbLoggerCategory.Database.Command.Name
        //], LogLevel.Information);
    }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Calendar>(entity =>
        {
            entity.HasKey(e => e.CalendarDate);

            entity.HasIndex(e => new { e.CalendarYear, e.Holiday }, "Calendar_IX_Calendar_Year_Holiday").IsDescending();

            entity.Property(e => e.CalendarDate)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.BusinessDay).HasColumnType("bit");
            entity.Property(e => e.CalendarDateDescription)
                .UseCollation("NOCASE")
                .HasColumnType("varchar(50)");
            entity.Property(e => e.DayOfWeekName)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("varchar(10)");
            entity.Property(e => e.FirstDateOfMonth)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.FirstDateOfQuarter)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.FirstDateOfWeek)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.FirstDateOfYear)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.Holiday).HasColumnType("bit");
            entity.Property(e => e.HolidayComputed)
                .IsRequired()
                .UseCollation("NOCASE")
                .HasColumnType("varchar(3)");
            entity.Property(e => e.LastDateOfMonth)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.LastDateOfQuarter)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.LastDateOfWeek)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.LastDateOfYear)
                .UseCollation("NOCASE")
                .HasColumnType("datetime");
            entity.Property(e => e.NonBusinessDay).HasColumnType("bit");
            entity.Property(e => e.Weekday).HasColumnType("bit");
            entity.Property(e => e.Weekend).HasColumnType("bit");
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}